easy_admin:
    site_name: 'JAVADAY <em style="font-size: 80%;">Адмiн</em>'
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'light'
        menu:
            - { entity: 'Event', icon: 'calendar' }
            - { entity: 'Sponsor', icon: 'usd' }
            - { entity: 'SponsorType', icon: 'list-ul' }
            - { entity: 'Speaker', icon: 'users' }
            - { entity: 'Photo', icon: 'photo' }
    entities:
        Event:
            class: App\Entity\Event
            label: 'Подiї'
            icon: calendar
            list:
                title: '%%entity_label%% список'
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content', type: 'ckeditor' }
        Sponsor:
            label: 'Спонсори'
            class: App\Entity\Sponsor
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'url' }
                    - { property: 'type' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'event' }
            list:
                title: '%%entity_label%% список'
                fields:
                    - { property: 'name' }
                    - { property: 'type' }
                    - { property: 'image', type: 'image', base_path: '/images/sponsors' }
                    - { property: 'event' }
        SponsorType:
            label: 'Категорiї спонсорiв'
            class: App\Entity\SponsorType
            form:
                fields:
                    - { property: 'name' }
        Speaker:
            label: 'Докладачi'
            class: App\Entity\Speaker
            form:
                fields:
                    - { property: 'id' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'name' }
                    - { property: 'company' }
                    - { property: 'role' }
                    - { property: 'weight' }
                    - { property: 'event' }
            list:
                fields:
                    - { property: 'name'}
                    - { property: 'role'}
                    - { property: 'company'}
                    - { property: 'photo', type: 'image', base_path: '/images/speakers' }
                    - { property: 'event' }
        Photo:
            label: 'Фотографiї'
            class: App\Entity\Photo
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'image', type: 'image', base_path: '/images/photos' }
                    - { property: 'event' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'event' }