easy_admin:
    site_name: 'JAVADAY <em style="font-size: 80%;">Адмiн</em>'
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'light'
        menu:
            - entity: 'Event'
              icon: 'calendar'
            - entity: 'Sponsor'
              children:
                - { entity: 'Sponsor', icon: 'usd', label: 'Всi спонсори' }
                - { entity: 'SponsorType', icon: 'list-ul' }
            - entity: 'Activity'
              children:
                - { entity: 'Activity', icon: 'usd', label: 'Всi доповiдi' }
                - { entity: 'ActivityDay', icon: 'tasks' }
            - entity: 'Speaker'
              icon: 'users'
    entities:
        Event:
            class: App\Entity\Event
            label: 'Подiї'
            icon: calendar
            list:
                title: '%%entity_label%% список'
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content', type: 'ckeditor' }
        Sponsor:
            label: 'Спонсори'
            class: App\Entity\Sponsor
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'url' }
                    - { property: 'type' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'event' }
            list:
                title: '%%entity_label%% список'
                fields:
                    - { property: 'name' }
                    - { property: 'type' }
                    - { property: 'image', type: 'image', base_path: '/images/sponsors' }
                    - { property: 'event' }
        SponsorType:
            label: 'Категорiї спонсорiв'
            class: App\Entity\SponsorType
            form:
                fields:
                    - { property: 'name' }
        Activity:
            label: 'Доповiдi'
            class: App\Entity\Activity
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'startedAt' }
                    - { property: 'endedAt' }
                    - { property: 'day' }
                    - { property: 'speaker' }
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'name' }
                    - { property: 'startedAt' }
                    - { property: 'endedAt' }
                    - { property: 'day' }
                    - { property: 'speaker' }
        ActivityDay:
            label: 'Днi заходу'
            class: App\Entity\ActivityDay
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'event' }
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'name' }
                    - { property: 'event' }

        Speaker:
            label: 'Доповiдачi'
            class: App\Entity\Speaker
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'company' }
                    - { property: 'role' }
                    - { property: 'weight' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'event' }
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'photo', type: 'image', base_path: '/images/speakers' }
                    - { property: 'name'}
                    - { property: 'role'}
                    - { property: 'company'}
                    - { property: 'event' }
        Photo:
            label: 'Фотографiї'
            class: App\Entity\Photo
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'image', type: 'image', base_path: '/images/photos' }
                    - { property: 'event' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'event' }