vich_uploader:
    db_driver: orm

    mappings:
        sponsor:
            uri_prefix: /images/sponsors
            upload_destination: '%kernel.project_dir%/public/images/sponsors'
        speaker:
            uri_prefix: /images/speakers
            upload_destination: '%kernel.project_dir%/public/images/speakers'
